<?php
  
	function get_statename($statecode=NULL){
		$state = array(
			'AFG' => 'Afghan',
			'ALB' => 'Albanian',
			'DZA' => 'Algerian',
			'ASM' => 'American',
			'AND' => 'Andorran',
			'AGO' => 'Angolan',
			'ATA' => 'Antiguans',
			'ARG' => 'Argentinean',
			'ARM' => 'Armenian',
			'AUS' => 'Australian',
			'AUT' => 'Austrian',
			'AZE' => 'Azerbaijani',
			'BHS' => 'Bahamian',
			'BHR' => 'Bahraini',
			'BGD' => 'Bangladeshi',
			'BRB' => 'Barbadian',
			'BLR' => 'Barbudans',
			'BEL' => 'Belgian',
			'BLZ' => 'Belizean',
			'BEN' => 'Beninese',
			'BTN' => 'Bhutanese',
			'BOL' => 'Bolivian',
			'BIH' => 'Bosnian',
			'BRA' => 'Brazilian',
			'GBR' => 'British',
			'BRN' => 'Bruneian',
			'BGR' => 'Bulgarian',
			'BFA' => 'Burkinabe',
			'BDI' => 'Burundian',
			'KHM' => 'Cambodian',
			'CMR' => 'Cameroonian',
			'CND' => 'Canadian',
			'CPV' => 'Cape Verdean',
			'CAF' => 'Central African',
			'TCD' => 'Chadian',
			'CHL' => 'Chilean',
			'CHN' => 'Chinese',
			'COL' => 'Colombian',
			'COM' => 'Comoran',
			'COG' => 'Congolese',
			'CRI' => 'Costa Rican',
			'HRV' => 'Croatian',
			'CUB' => 'Cuban',
			'CYP' => 'Cypriot',
			'CZE' => 'Czech',
			'DNK' => 'Danish',
			'DJI' => 'Djibouti',
			'DMA' => 'Dominican',
			'DNK' => 'Dutch',
			'TMP' => 'East Timorese',
			'ECU' => 'Ecuadorean',
			'EGY' => 'Egyptian',
			'GNQ' => 'Equatorial Guinean',
			'ERI' => 'Eritrean',
			'EST' => 'Estonian',
			'ETH' => 'Ethiopian',
			'FJI' => 'Fijian',
			'PHL' => 'Filipino',
			'FIN' => 'Finnish',
			'FRA' => 'French',
			'GAB' => 'Gabonese',
			'GMB' => 'Gambian',
			'GEO' => 'Georgian',
			'DEU' => 'German',
			'GHA' => 'Ghanaian',
			'GRC' => 'Greek',
			'GRL' => 'Grenadian',
			'GTM' => 'Guatemalan',
			'GNB' => 'Guinea-Bissauan',
			'GIN' => 'Guinean',
			'GUY' => 'Guyanese',
			'HTI' => 'Haitian',
			'HMD' => 'Herzegovinian',
			'HND' => 'Honduran',
			'HUN' => 'Hungarian',
			'ISL' => 'Icelander',
			'IND' => 'Indian',
			'IDN' => 'Indonesian',
			'IRN' => 'Iranian',
			'IRQ' => 'Iraqi',
			'IRL' => 'Irish',
			'ISR' => 'Israeli',
			'ITA' => 'Italian',
			'JAM' => 'Jamaican',
			'JPN' => 'Japanese',
			'JOR' => 'Jordanian',
			'KAZ' => 'Kazakhstani',
			'KEN' => 'Kenyan',
			'KWT' => 'Kuwaiti',
			'KGZ' => 'Kyrgyz',
			'LAO' => 'Laotian',
			'LVA' => 'Latvian',
			'LBN' => 'Lebanese',
			'LBR' => 'Liberian',
			'LBY' => 'Libyan',
			'LIE' => 'Liechtensteiner',
			'LTU' => 'Lithuanian',
			'LUX' => 'Luxembourger',
			'MKD' => 'Macedonian',
			'MDG' => 'Malagasy',
			'MWI' => 'Malawian',
			'MYS' => 'Malaysian',
			'MDV' => 'Maldivan',
			'MLI' => 'Malian',
			'MLT' => 'Maltese',
			'MHL' => 'Marshallese',
			'MRT' => 'Mauritanian',
			'MUS' => 'Mauritian',
			'MEX' => 'Mexican',
			'FSM' => 'Micronesian',
			'MDA' => 'Moldovan',
			'MCO' => 'Monacan',
			'MNG' => 'Mongolian',
			'MAR' => 'Moroccan',
			'MOZ' => 'Mozambican',
			'NAM' => 'Namibian',
			'NRU' => 'Nauruan',
			'NPL' => 'Nepalese',
			'NLD' => 'Netherlander',
			'NZL' => 'New Zealander',
			'NIC' => 'Nicaraguan',
			'NGA' => 'Nigerian',
			'NOR' => 'Norwegian',
			'OMN' => 'Omani',
			'PAK' => 'Pakistani',
			'PLW' => 'Palauan',
			'PAN' => 'Panamanian',
			'PNG' => 'Papua New Guinean',
			'PRY' => 'Paraguayan',
			'PER' => 'Peruvian',
			'POL' => 'Polish',
			'PRT' => 'Portuguese',
			'QAT' => 'Qatari',
			'ROM' => 'Romanian',
			'RUS' => 'Russian',
			'RWA' => 'Rwandan',
			'LCA' => 'Saint Lucian',
			'WSM' => 'Samoan',
			'SMR' => 'San Marinese',
			'STP' => 'Sao Tomean',
			'SAU' => 'Saudi',
			'SEN' => 'Senegalese',
			'SLE' => 'Serbian',
			'SYC' => 'Seychellois',
			'SLE' => 'Sierra Leonean',
			'SGP' => 'Singaporean',
			'SVK' => 'Slovakian',
			'SVN' => 'Slovenian',
			'SLB' => 'Solomon Islander',
			'SOM' => 'Somali',
			'ZAF' => 'South African',
			'ESP' => 'Spanish',
			'LKA' => 'Sri Lankan',
			'SDN' => 'Sudanese',
			'SUR' => 'Surinamer',
			'SWZ' => 'Swazi',
			'SWE' => 'Swedish',
			'CHE' => 'Swiss',
			'SYR' => 'Syrian',
			'TWN' => 'Taiwanese',
			'TJK' => 'Tajik',
			'TZA' => 'Tanzanian',
			'THA' => 'Thai',
			'TGO' => 'Togolese',
			'TON' => 'Tongan',
			'TTO' => 'Trinidadian or Tobagonian',
			'TUN' => 'Tunisian',
			'TUR' => 'Turkish',
			'TUV' => 'Tuvaluan',
			'UGA' => 'Ugandan',
			'UKR' => 'Ukrainian',
			'URY' => 'Uruguayan',
			'UZB' => 'Uzbekistani',
			'VEN' => 'Venezuelan',
			'VNM' => 'Vietnamese',
			'WLF' => 'Welsh',
			'YEM' => 'Yemenite',
			'ZMB' => 'Zambian',
			'ZWE' => 'Zimbabwean'
			
		);		
		
		$statecode=strtoupper($statecode);
		
		if($statecode)
			return $state[$statecode];		
		else
			return $state;
	}
	
	function get_statecode($state){
	
		$state_codes = array(
				'Alabama' => 'AL',
				'Alaska' => 'AK',
				'Arizona' => 'AZ',
				'Arkansas' => 'AR',
				'California' => 'CA',
				'Colorado' => 'CO',
				'Connecticut' => 'CT',
				'Delaware' => 'DE',
				'District of Columbia' => 'DC',
				'Florida' => 'FL',
				'Georgia' => 'GA',
				'Hawaii' => 'HI',
				'Idaho' => 'ID',
				'Illinois' => 'IL',
				'Indiana' => 'IN',
				'Iowa' => 'IA',
				'Kansas' => 'KS',
				'Kentucky' => 'KY',
				'Louisiana' => 'LA',
				'Maine' => 'ME',
				'Maryland' => 'MD',
				'Massachusetts' => 'MA',
				'Michigan' => 'MI',
				'Minnesota' => 'MN',
				'Mississippi' => 'MS',
				'Missouri' => 'MO',
				'Montana' => 'MT',
				'Nebraska' => 'NE',
				'Nevada' => 'NV',
				'New Hampshire' => 'NH',
				'New Jersey' => 'NJ',
				'New Mexico' => 'NM',
				'New York' => 'NY',
				'North Carolina' => 'NC',
				'North Dakota' => 'ND',
				'Ohio' => 'OH',
				'Oklahoma' => 'OK',
				'Oregon' => 'OR',
				'Pennsylvania' => 'PA',
				'Rhode Island' => 'RI',
				'South Carolina' => 'SC',
				'South Dakota' => 'SD',
				'Tennessee' => 'TN',
				'Texas' => 'TX',
				'Utah' => 'UT',
				'Vermont' => 'VT',
				'Virginia' => 'VA',
				'Washington' => 'WA',
				'West Virginia' => 'WV',
				'Wisconsin' => 'WI',
				'Wyoming' => 'WY'
				);	
			return $state_codes[$state];
	}
	
	function capitalize_firstChar($word){
		$word=ucfirst(strtolower($word));
		return $word;
	}

	function findGender($uid=NULL)
	{
		if($uid)
		{
			$sql_gend="SELECT `memb_gender` FROM `med_members` WHERE `memb_id`='$uid'";
			$rs_gend=mysql_query($sql_gend);
			$row_gend=mysql_fetch_assoc($rs_gend);
			$gender=$row_gend['memb_gender'];
		}
		return strtolower($gender);
	}

?>